services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dotnet-sdk-9-preview
    volumes:
      - ./:/course
    ports:
      - "5000:5000"
    working_dir: /course
    command: [ "bash" ]
    tty: true
